name: Python CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Databricks Bundle #Run Python Script
        run: | #python hello.py
          test -f databricks.yml
          test -f notebooks/customer_load.py
          echo "Databricks bundle validation successful"